name: Implementation report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/r2rml4net/test-cases.git --depth 1
      - uses: actions/setup-node@v1
        with:
          node-version: '13'

      # TODO: add steps to set require environment

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.0
        with:
          java-version: 13
      - run: docker-compose up -d
      - run: yarn

      # TODO: add steps to bootstrap your implementation

      - run: ./index.js
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: test-cases/**/*-*.ttl
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports/earl*.ttl
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.1
        with:
          build_dir: reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
